config/routes.rb
Rails.application.routes.draw do

  root to: 'home#front'
  
  resources :questions do
    member do
      get "claim"
      get "unclaim"
    end
  end

  resources :users, only: [:index, :create]
  resources :admin_sessions, only: [:create]

  get 'signin', to: 'users#new'
  get 'signout', to: 'users#destroy'
  get 'admin_signin', to: 'admin_sessions#new'
  get 'admin_signout', to: 'admin_sessions#destroy'

  get 'home', controller: 'home'

  get 'ui(/:action)', controller: 'ui'
  
  get '*path', to: 'home#front'

end

app/models/question.rb
class Question < ActiveRecord::Base
  include ActionView::Helpers::DateHelper
  include DeliSupport
  
  belongs_to :user
  
  validates :title, :body, presence: true

  def age_string
    time_ago_in_words(self.created_at) + " ago"
  end

  def posted_on_string
    " on " + pretty_time_string(created_at)
  end


  def self.active_question
    Question.find_by(claimed: true)
  end

  def self.unclaimed_questions
    return_set = Question.all.where("claimed = 'f'").order(created_at: :asc)
    return_set.size == 0 ? nil : return_set
  end

  def self.get_order_position_string(question)
    question_list = unclaimed_questions

    return "not in the queue" unless question_list

    index = question_list.find_index(question)
    case index
    when nil
      return "not in the queue"
    when 0
      return "next in the queue"
    else
      return (index + 1).ordinalize
    end
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  before_action :require_user, except: [:index, :show, :claim, :unclaim, :destroy]
  before_action :require_user_or_admin, only: [:destroy]
  before_action :require_admin_user, only: [:claim, :unclaim]

  def index
    @unclaimed_questions = Question.all.where("claimed = 'f'").order(created_at: :asc)
    @active_question = Question.find_by(claimed: true)
  end

  def show
    @question = verify_question_id(params[:id], false)
  end


  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    @question.user = current_user_get
    if (@question.save)
      flash[:success] = "Your question is now in #{Question.get_order_position_string(@question)} place"
      redirect_to questions_path
    else
      render :new
    end
  end

  def edit
    @question = verify_question_id(params[:id])
  end

  def update
    @question = verify_question_id(params[:id])
    return unless @question

    if (@question.update(question_params))
      flash[:success] = "Your question has been updated."
      redirect_to questions_path
    else
      render :edit
    end
  end

  def destroy
    @question = verify_question_id(params[:id], (admin_logged_in? ? false : true))
    return unless @question    
    
    username = @question.user.username
    @question.destroy

    if (admin_logged_in?)
      flash[:success] = "User #{username}'s question (#{@question.title}) was deleted"
    else
      flash[:success] = "Your question (#{@question.title}) was deleted"
    end

    redirect_to questions_path
  
  end

  def unclaim
    question = verify_question_id(params[:id], false)
    return unless question

    if (question != Question.active_question)
      flash[:danger] = "You can only unclaim an already claimed question"
      redirect_to questions_path
    else
      question.claimed = false
      question.save
      flash[:success] = "You have unclaimed the question (#{question.title})."
      redirect_to questions_path
    end
  end

  def claim
    question = verify_question_id(params[:id], false)
    return unless question

    if (Question.active_question && (question != Question.active_question))
      flash[:danger] = "There is already claimed question."
      redirect_to questions_path
    else
      question.claimed = true
      question.save
      flash[:success] = "You have claimed the question (#{question.title})."
      redirect_to questions_path
    end

  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end

  def verify_question_id(id_string, for_edit_or_destroy=true)
    question = Question.find_by(id: id_string)
    
    case
    when question.nil?
      flash[:danger] = "There is no such question in the system"
      redirect_to questions_path
      return nil
    when (question.user != current_user_get) && for_edit_or_destroy
      flash[:danger] = "You cannot edit or delete another user's question"
      redirect_to questions_path
      return nil
    when (question == Question.active_question) && for_edit_or_destroy
      flash[:danger] = "You cannot edit or delete a question that has already been claimed by a TA"
      redirect_to questions_path
      return nil
    else
      return question
    end
  end

end

app/views/questions/_question_entry.html.haml
%tr
  %td
    = index + 1
  %td
    = question.user.username
  %td
    = link_to(question.title, question_path(question), id: "question-title-#{question.id}")

  %td
    %small
      %em= timeago(question.created_at)     
  %td
    - if question.user == current_user_get
      = icon_action_link("pencil", "Edit", edit_question_path(question), {id: "edit-question-#{question.id}"} )
      %br
      = icon_action_link("trash", "Cancel", question_path(question), {method: :delete, data: { confirm: "Are you sure you want to cancel this question?" }, id: "delete-question-#{question.id}"})
    - if admin_logged_in? && Question.active_question.nil?
      = icon_action_link("asterisk", "Claim", claim_question_path(question), {id: "claim-question-#{question.id}"})

app/views/questions/_question_form.html.haml
- button_text ||= "Submit"

.well
  %h2
    Enter Your Question

  = bootstrap_form_for(@question) do |f|
    = f.text_field :title, {label: "One-Liner", cols: 50}
    = f.text_area :body, label: "Details", rows: 8, cols: 50
    = f.submit button_text, class: "btn btn-success"

app/views/questions/edit.html.haml
= render "question_form", button_text: "Update Question"

app/views/questions/index.html.haml
.well
  %header
    %h2 Hangout Queue

.well
  %header
    %h3
      Active Question
    - if @active_question
      %strong(style="margin-left: 80px;")
        = "User: #{@active_question.user.username}"
      %br
      %strong(style="margin-left: 80px;")
        One-Liner:
      %span(style="margin-right: 80px; margin-left: 40px;")
        %em(id="active-question-title-#{@active_question.id}")= @active_question.title
      .well(style="margin-top: 40px; margin-left: 80px; margin-right: 120px;" id="active-question-body-#{@active_question.id}")
        = @active_question.body
      - if admin_logged_in?
        = icon_action_link_large("eject", "Unclaim", unclaim_question_path(@active_question), {id: "unclaim-question-id"})
        %br
        %br
        = icon_action_link_large("check", "Complete", question_path(@active_question), {method: :delete, data: { confirm: "Are you sure?" }, id: "complete-question-id" })
        %br

    - else
      %strong(style="margin-left: 80px;")
        No question has been claimed yet.

.well
  %table.well.table.table-condensed
    %tr
      %th(width="5%") Position
      %th(width="20%") User
      %th(width="40%") One-Liner
      %th(width="20%") When Submitted
      %th(width="15%" style="text-align: right; padding-right: 15px;") Action
    - @unclaimed_questions.each_with_index do |question, index|
      = render "question_entry", { question: question, index: index }

app/views/questions/new.html.haml
= render "question_form", button_text: "Submit New Question"

app/views/questions/show.html.haml
.well
  %h2
    Question Details
.well
  .row(style="margin-left: 20px;")
    %label(style="margin-right: 40px;") Posted by
    = "#{@question.user.username}"
    %em= "#{@question.posted_on_string}"
    = "(#{timeago(@question.created_at)})".html_safe
    %hr
    %label(style="margin-right: 40px;") One-Liner
    %label= @question.title
  .row(style="margin-left: 20px;")
    %hr
    %label(style="margin-right: 40px;") Details
    %br
    %p(style="margin-left: 90px;")=  @question.body
