config/routes.rb
Rails.application.routes.draw do

  root to: 'home#front'
  
  resources :questions do
    member do
      get "claim"
      get "unclaim"
    end
  end

  resources :users, only: [:index, :create]
  resources :admin_sessions, only: [:create]

  get 'signin', to: 'users#new'
  get 'signout', to: 'users#destroy'
  get 'admin_signin', to: 'admin_sessions#new'
  get 'admin_signout', to: 'admin_sessions#destroy'

  get 'home', controller: 'home'

  get 'ui(/:action)', controller: 'ui'
  
  get '*path', to: 'home#front'

end

app/views/shared/_header.html.haml
%ul.nav(style="margin-top: 10px;")
  %li
    .btn-group.nav_item
      = link_to "View Queue", questions_path, class: "btn btn-primary btn-small", style: "padding-bottom: 6px;", id: "view-queue"
  %li
    .btn-group.nav_item
      - if !admin_logged_in?
        = link_to "Enter Question", new_question_path, class: "btn btn-success btn-small", style: "padding-bottom: 6px;", id: "new-question-button"
  %li
    .btn-group.nav_item
      = link_to "View Participants", users_path, class: "btn btn-primary btn-small", style: "padding-bottom: 6px;"

  %li
    .btn-group.nav_item
      - if logged_in? || admin_logged_in?
        = link_to "#", class: "btn btn-primary btn-small dropdown-toggle", "data-toggle" => "dropdown", style: "padding-bottom: 6px;" do
          - if logged_in?
            = ("&nbsp;" + current_user_get.username + "&nbsp;&nbsp;").html_safe
          - else
            = ("&nbsp;" + current_admin_user_get.username + "&nbsp;&nbsp;").html_safe
          %span(class="caret")

        %ul.dropdown-menu
          %li
            - if logged_in?
              = link_to "Sign Out", signout_path, data: { confirm: "Are you sure you want to sign out?  All of your pending questions will be cancelled." }
            - else
              = link_to "Sign Out", admin_signout_path
      - else
        = link_to "Sign In", signin_path, class: "btn btn-primary btn-small", style: "padding-bottom: 6px;"

%hr

app/views/shared/_messages.html.haml
- flash.each do |name, msg|
  %div(class="alert alert-#{name}")
    %a.close(data-dismiss='alert') &#215;
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)