config/routes.rb
Rails.application.routes.draw do

  root to: 'home#front'
  
  resources :questions do
    member do
      get "claim"
      get "unclaim"
    end
  end

  resources :users, only: [:index, :create]
  resources :admin_sessions, only: [:create]

  get 'signin', to: 'users#new'
  get 'signout', to: 'users#destroy'
  get 'admin_signin', to: 'admin_sessions#new'
  get 'admin_signout', to: 'admin_sessions#destroy'

  get 'home', controller: 'home'

  get 'ui(/:action)', controller: 'ui'
  
  get '*path', to: 'home#front'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end

  def front
    redirect_to home_path if (logged_in? || admin_logged_in?)
  end

end

app/views/home/front.html.haml
%section.site_title
  %h1
    Sign in to get in line for questions
  %p
    = link_to "Sign In", signin_path, class: "btn btn-success btn-large", style: "font-size: 32px; margin-top: 8px; margin-left: 40px; padding-left: 20px; padding-top: 20px; padding-bottom: 20px; padding-right: 20px;"
  %h2(style="margin-top: 100px;")
    %em If you are an admin, sign in via the admin page to start claiming questions
  %p
    = link_to "Admin Sign In", admin_signin_path, class: "btn btn-primary btn-large", style: "font-size: 32px; margin-top: 8px; margin-left: 40px; padding-left: 20px; padding-top: 20px; padding-bottom: 20px; padding-right: 20px;"

app/views/home/home.html.haml
.well
  - if !admin_logged_in?
    = link_to "Add Question to Queue", new_question_path, class: "btn btn-primary btn-large", style: "font-size: 32px; margin-top: 8px; margin-left: 40px; padding-left: 20px; padding-top: 20px; padding-bottom: 20px; padding-right: 20px;"
  %br
  = link_to "View Queue", questions_path, class: "btn btn-primary btn-large", style: "font-size: 32px; margin-top: 8px; margin-left: 40px; padding-left: 20px; padding-top: 20px; padding-bottom: 20px; padding-right: 20px;"
  %br
  = link_to "See Users", users_path, class: "btn btn-primary btn-large", style: "font-size: 32px; margin-top: 8px; margin-left: 40px; padding-left: 20px; padding-top: 20px; padding-bottom: 20px; padding-right: 20px;"